### ISSUE TITLE
Avoid extra /*.json to API calls / more REST friendly

### ISSUE THREAD

**Issue by benoitf** [eclipse/che-plugin-registry#26]
Today to get list of plug-ins, the remote call is
`http://localhost:8080/index.json`

it would be nice to cut the `/index.json` path to be more REST friendly

`http://localhost:8080/plugins`  would list all the plug-ins

Also http://localhost:8080/ could display the README.

And to grab data for a specific plug-in:
today we have:
```
http://localhost:8080/plugins/org.eclipse.che.editor.theia/1.0.0/meta.yaml
```

it would be nice to have
```
http://localhost:8080/plugins/org.eclipse.che.editor.theia/1.0.0 ?
```

```(<plugin-id>/<plugin-version>)```

and call to 
```
http://localhost:8080/plugins/org.eclipse.che.editor.theia
```
would list all versions

**Comment by garagatyi** [comment]
Already fixed.
