### ISSUE TITLE
New Plugins are not displayed in index list

### ISSUE THREAD

**Issue by gollapudi2009** [eclipse/che-plugin-registry#333]
I tried to add a meta.yml for the vscode extension in v3/plugins/{publisher}/{plugin-name}/{version}/ directory... but, it is not showing up in the index list.  What am I doing wrong?

Following is the meta.yaml

```
publisher: GabrielBB
apiVersion: v3
version: 0.9.9
type: VS Code extension
name: vscode-lombok
displayName: Lombok 
title: Lombok Annotations.
description: TA lightweight extension to support Lombok annotations processing in Visual Studio Code.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: Language
repository: https://github.com/GabrielBB/vscode-lombok
firstPublicationDate: '2018-03-11'
spec:
  extensions:
    - vscode:extension/GabrielBB.vscode-lombok
latestUpdateDate: "2019-09-14"
```

**Comment by amisevsk** [comment]
The two easy checks I can think of are:
- The index is generated at build time, currently; if you are looking to add your plugin to the registry itself you will need to rebuild it (see the readme and `build.sh` for guidance there)
- The index is pulled by Che on load and reused -- to pick up changes you need to refresh your browser.

If it's not one of the two above issues, we can look into it further. Also, note that you can use your plugin without including it in the registry, by providing a direct link to the raw yaml, e.g.
```yaml
components:
- type: chePlugin
  reference: <url to your meta.yaml, e.g. on github or pastebin>
```

Also, for more visibility to the team/easier planning, we are generally creating issues only in the mainline eclipse/che repository (so we should move this issue there).

**Comment by nickboldt** [comment]
Is this still an issue @gollapudi2009 ? If so, we can move this issue to the main Che issues planner. 

If not, we'll close this as "issues was explained, user error."

**Comment by ericwill** [comment]
> Is this still an issue @gollapudi2009 ? If so, we can move this issue to the main Che issues planner.
> 
> If not, we'll close this as "issues was explained, user error."

There hasn't been a response here in awhile, I'm going to close this.
