### ISSUE TITLE
Meta files must contain field `type` for Che to be able to recognize what broker to use with it

### ISSUE THREAD

**Issue by garagatyi** [eclipse/che-plugin-registry#41]

**Comment by skabashnyuk** [comment]
What is the list of possible values?

**Comment by skabashnyuk** [comment]
Just checked. All meta.yaml already contains filed type. Can you specify what exactly do you want to do? Do you want to add pre commit/pre build checks?

**Comment by l0rd** [comment]
I don't know if it's what you meant @garagatyi but I am +1 to replace `type` with `broker`. The value of `broker` should be the broker's docker image.

**Comment by garagatyi** [comment]
@skabashnyuk I mean that we don't fail CI if the type is missing and it is required for the latest changes in the brokering process where several brokers are used for dealing with several types of plugins.

@l0rd overall it would be nice to have something like that, but there are things that we need to consider before doing so:
- the current code doesn't respect it and making this breaking change might delay the delivery of a working WS.NEXT flow to OSIO
- hardcoding broker image version would mean that somebody has to update meta files when new bugfix broker is released. This is hard to maintain. I would rather stick to types of plugins which would be properly handled by a set of brokers what info we can also store in the registry somehow and would be able to update it everytime we want without updating tons of plugins metafiles.
- it might be hard for a user to know what is a suitable and up-to-date version of a broker image. Instead of that, we can offer automatic matching against the set of common brokers for a plugin with known type and an ability to override image of the broker that needs to be used to process a particular plugin.

**Comment by skabashnyuk** [comment]
@garagatyi I'm still not quite sure what is the goal of this issue.

**Comment by garagatyi** [comment]
The goal is to make sure that no meta without field `type` is merged.

**Comment by garagatyi** [comment]
Out of date, closing
