### ISSUE TITLE
Handle more metadatas for the plugin viewer

### ISSUE THREAD

**Issue by slemeur** [eclipse/che-plugin-registry#71]
### Goal
The plugin viewer allows to display a lot of metadatas about the plugins. We need the plugin-registry to allow a plugin contributor to provide those metadatas so they can be exposed by the api and displayed to the end-user is the plugin viewer.

### Visual mockups of the Plugin Viewer
https://redhat.invisionapp.com/share/J8PGG7D7TFP#/screens

### Metadata needed
Each plugin will need to provide the following information

| Property | Description  |
|---|---|
| Title |  Title of the plugin |
| Publisher | Name of the author of the plugin |
| Category | Category of the pluginName of the author of the plugin |
| Icon | Plugin icon (in svg) |
| Short-Description | Short description of the plugin |
| Preview | Link to a repository with a devfile, show casing the plugin for a particular sample project |
| Repository | Link to the repository of the plugin |
| First Publication Date | Date of the first publication of the plugin in the registry |
| Latest Updated | Date of the latest update of the plugin registry |
| Tags | A list of key words related to the plugin |
| Media-img | A list of links pointing to screenshoots of the plugins |
| Media-video | A list of links pointing to videos of the plugins |

We should have a define set of categories:
- Editor
- Debugger
- Formatter
- Language
- Linter
- Snippet
- Theme
- Other

**Comment by skabashnyuk** [comment]
@slemeur can you clarify the scope of this task.
Do we need to add/check if exists 
- Title
- Publisher 
- Category
- Icon
- Short-Description
- Preview 
- Repository
- First Publication Date
-  Latest Updated
- Tags
- Media-img
- Media-video 

to each meta.yaml? Are they all mandatory?

**Comment by slemeur** [comment]
- preview
- media-img
- media-video 
- tags
could be optional. 

All others are mandatory.

**Comment by mkuznyetsov** [comment]
A typical plugin yaml that would be provided by the registry:
```
id: org.eclipse.che.editor.theia
version: 1.0.0
type: Che Editor
name: theia-ide
title: Eclipse Theia for Eclipse Che
description: Eclipse Theia
icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
url: https://github.com/ws-skeleton/che-editor-theia/releases/download/untagged-2218dafda12e0786aa79/che-editor-plugin.tar.gz
publisher: Red Hat, Inc.
category: Editor
repository: https://github.com/ws-skeleton/che-editor-theia/
firstPublicationDate: "2019-01-17"
latestUpdateDate: "2019-01-17"
```

**Comment by mkuznyetsov** [comment]
@slemeur @l0rd  just to make sure - are you ok with the name of new fields in YAML as in the given example? I assume it would be in line with the style/case of other already existing fields in it.

**Comment by l0rd** [comment]
@mkuznyetsov your example looks good to me
@garagatyi I would go with camelCase for every field in meta.yaml and che-plugin.yaml for consistency with devfile and kubernetes resources definitions in general

**Comment by garagatyi** [comment]
Created an issue for that https://github.com/eclipse/che/issues/12501

**Comment by sleshchenko** [comment]
@mkuznyetsov Is it already fixed?

**Comment by sleshchenko** [comment]
It would be nice to have fields description(name, description, optional/required) and meta.yaml full example in README.md of the che-plugin-registry repository.

**Comment by mkuznyetsov** [comment]
Plugin Registry for openshift.io now runs with new version of plugin registry (with new plugin viewer fields)
As well as Che 6.18.2, which is compatible with it, so this issue can be close
