### ISSUE TITLE
Where is the valid location for `index.json` ?

### ISSUE THREAD

**Issue by monaka** [eclipse/che-plugin-registry#89]
Referring to https://github.com/eclipse/che-plugin-registry/blame/11cf2e16c2851056c35fcf0d2ef365e26b7c507c/README.md#L60 .

```
curl  "http://localhost:8080/index.json"
```

But there is no `index.json` on openshift.io.

```
curl https://che-plugin-registry.openshift.io/index.json
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /index.json was not found on this server.</p>
</body></html>
```

`curl https://che-plugin-registry.openshift.io/plugins/index.json` works. 

Which should be fixed, `README.md` or code ?

**Comment by skabashnyuk** [comment]
valid location http://localhost:8080/plugins/index.json
related PR https://github.com/eclipse/che-plugin-registry/pull/80
